{"cause":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"ac-emxgxve-shard-00-00.krws5zk.mongodb.net:27017":{"$clusterTime":null,"address":"ac-emxgxve-shard-00-00.krws5zk.mongodb.net:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":262342946,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"ac-emxgxve-shard-00-01.krws5zk.mongodb.net:27017":{"$clusterTime":null,"address":"ac-emxgxve-shard-00-01.krws5zk.mongodb.net:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":262343322,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"ac-emxgxve-shard-00-02.krws5zk.mongodb.net:27017":{"$clusterTime":null,"address":"ac-emxgxve-shard-00-02.krws5zk.mongodb.net:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":262343170,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-qotjc1-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"errorLabelSet":{},"level":"error","message":"MongoDB connection error: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/","reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{"ac-emxgxve-shard-00-00.krws5zk.mongodb.net:27017":{"$clusterTime":null,"address":"ac-emxgxve-shard-00-00.krws5zk.mongodb.net:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":262342946,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"ac-emxgxve-shard-00-01.krws5zk.mongodb.net:27017":{"$clusterTime":null,"address":"ac-emxgxve-shard-00-01.krws5zk.mongodb.net:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":262343322,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"},"ac-emxgxve-shard-00-02.krws5zk.mongodb.net:27017":{"$clusterTime":null,"address":"ac-emxgxve-shard-00-02.krws5zk.mongodb.net:27017","arbiters":[],"electionId":null,"error":{"beforeHandshake":false,"errorLabelSet":{}},"hosts":[],"iscryptd":false,"lastUpdateTime":262343170,"lastWriteDate":0,"logicalSessionTimeoutMinutes":null,"maxBsonObjectSize":null,"maxMessageSizeBytes":null,"maxWireVersion":0,"maxWriteBatchSize":null,"me":null,"minRoundTripTime":0,"minWireVersion":0,"passives":[],"primary":null,"roundTripTime":-1,"setName":null,"setVersion":null,"tags":{},"topologyVersion":null,"type":"Unknown"}},"setName":"atlas-qotjc1-shard-0","stale":false,"type":"ReplicaSetNoPrimary"},"stack":"MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n    at _handleConnectionErrors (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\mongoose\\lib\\connection.js:1165:11)\n    at NativeConnection.openUri (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\mongoose\\lib\\connection.js:1096:11)\n    at async connectDB (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\utils\\db.ts:10:5)\n    at async startServer (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\index.ts:53:5)","timestamp":"2025-09-01T07:59:48.115Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_limit_value\":\"0\",\"consumer\":\"projects/446709098246\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_location\":\"europe-west1\",\"service\":\"generativelanguage.googleapis.com\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_limit_value\":\"0\",\"consumer\":\"projects/446709098246\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_location\":\"europe-west1\",\"service\":\"generativelanguage.googleapis.com\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-01T21:37:12.469Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\",\"quota_limit_value\":\"0\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"consumer\":\"projects/446709098246\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_location\":\"europe-west1\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\",\"quota_limit_value\":\"0\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"consumer\":\"projects/446709098246\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_location\":\"europe-west1\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T04:40:20.949Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_location\":\"europe-west1\",\"quota_limit_value\":\"0\",\"consumer\":\"projects/446709098246\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_location\":\"europe-west1\",\"quota_limit_value\":\"0\",\"consumer\":\"projects/446709098246\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T05:15:31.988Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"service\":\"generativelanguage.googleapis.com\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"consumer\":\"projects/446709098246\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_limit_value\":\"0\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"service\":\"generativelanguage.googleapis.com\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"consumer\":\"projects/446709098246\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_limit_value\":\"0\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T05:25:23.909Z"}
{"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"inn.gs","syscall":"getaddrinfo"},"level":"error","message":"Failed to send mood update event: fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:15422:13\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async body.maxAttempts.maxAttempts (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:674:26)\n    at async retryWithBackoff (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\helpers\\promises.ts:247:14)\n    at async Inngest._send (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:667:18)\n    at async sendMoodUpdateEvent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\utils\\inngestEvents.ts:29:5)\n    at async createMood (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\moodController.ts:33:5)","timestamp":"2025-09-02T05:30:21.854Z"}
{"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"inn.gs","syscall":"getaddrinfo"},"level":"error","message":"Unexpected error: fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:15422:13\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async body.maxAttempts.maxAttempts (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:674:26)\n    at async retryWithBackoff (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\helpers\\promises.ts:247:14)\n    at async Inngest._send (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:667:18)\n    at async sendMoodUpdateEvent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\utils\\inngestEvents.ts:29:5)\n    at async createMood (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\moodController.ts:33:5)","timestamp":"2025-09-02T05:30:21.858Z"}
{"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"inn.gs","syscall":"getaddrinfo"},"level":"error","message":"Failed to send mood update event: fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:15422:13\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async body.maxAttempts.maxAttempts (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:674:26)\n    at async retryWithBackoff (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\helpers\\promises.ts:247:14)\n    at async Inngest._send (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:667:18)\n    at async sendMoodUpdateEvent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\utils\\inngestEvents.ts:29:5)\n    at async createMood (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\moodController.ts:33:5)","timestamp":"2025-09-02T05:30:28.367Z"}
{"cause":{"code":"ENOTFOUND","errno":-3008,"hostname":"inn.gs","syscall":"getaddrinfo"},"level":"error","message":"Unexpected error: fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:15422:13\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async body.maxAttempts.maxAttempts (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:674:26)\n    at async retryWithBackoff (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\helpers\\promises.ts:247:14)\n    at async Inngest._send (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\src\\components\\Inngest.ts:667:18)\n    at async sendMoodUpdateEvent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\utils\\inngestEvents.ts:29:5)\n    at async createMood (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\moodController.ts:33:5)","timestamp":"2025-09-02T05:30:28.369Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_unit\":\"1/min/{project}/{region}\",\"service\":\"generativelanguage.googleapis.com\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_limit_value\":\"0\",\"consumer\":\"projects/446709098246\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_unit\":\"1/min/{project}/{region}\",\"service\":\"generativelanguage.googleapis.com\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_limit_value\":\"0\",\"consumer\":\"projects/446709098246\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T05:35:05.841Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"consumer\":\"projects/446709098246\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_limit_value\":\"0\",\"service\":\"generativelanguage.googleapis.com\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"consumer\":\"projects/446709098246\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_limit_value\":\"0\",\"service\":\"generativelanguage.googleapis.com\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T05:51:32.023Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"consumer\":\"projects/446709098246\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_limit_value\":\"0\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"service\":\"generativelanguage.googleapis.com\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"quota_location\":\"europe-west1\",\"consumer\":\"projects/446709098246\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_unit\":\"1/min/{project}/{region}\",\"quota_limit_value\":\"0\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"service\":\"generativelanguage.googleapis.com\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T05:57:40.911Z"}
{"errorDetails":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","domain":"googleapis.com","metadata":{"consumer":"projects/446709098246","quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"europe-west1","quota_metric":"generativelanguage.googleapis.com/generate_content_requests","quota_unit":"1/min/{project}/{region}","service":"generativelanguage.googleapis.com"},"reason":"RATE_LIMIT_EXCEEDED"},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}],"level":"error","message":"Error in sendMessage: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_unit\":\"1/min/{project}/{region}\",\"consumer\":\"projects/446709098246\",\"quota_limit_value\":\"0\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_location\":\"europe-west1\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:446709098246'. [{\"@type\":\"type.googleapis.com/google.rpc.ErrorInfo\",\"reason\":\"RATE_LIMIT_EXCEEDED\",\"domain\":\"googleapis.com\",\"metadata\":{\"service\":\"generativelanguage.googleapis.com\",\"quota_metric\":\"generativelanguage.googleapis.com/generate_content_requests\",\"quota_unit\":\"1/min/{project}/{region}\",\"consumer\":\"projects/446709098246\",\"quota_limit_value\":\"0\",\"quota_limit\":\"GenerateContentRequestsPerMinutePerProjectPerRegion\",\"quota_location\":\"europe-west1\"}},{\"@type\":\"type.googleapis.com/google.rpc.Help\",\"links\":[{\"description\":\"Request a higher quota limit.\",\"url\":\"https://cloud.google.com/docs/quotas/help/request_increase\"}]}]\n    at handleResponseNotOk (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async sendMessage (C:\\Users\\hawip\\Desktop\\Lumo\\lumo\\backend\\src\\controllers\\chat.ts:133:28)","status":429,"statusText":"Too Many Requests","timestamp":"2025-09-02T06:00:21.090Z"}
